### PR TITLE
Let's Encrypt fix, redirects, custom cert, go1.9

### LINKED ISSUE #14: Disabled HTTP if TLS is enabled?

### LINKED ISSUE #15: Project does not build with Go 1.9
The project does not build with Go 1.9 using the vendored copy of x/net/http2
```
% go build
# github.com/briandowns/simple-httpd/vendor/golang.org/x/net/http2
vendor/golang.org/x/net/http2/go19.go:14:3: s.RegisterOnShutdown undefined (type *http.Server has no field or method RegisterOnShutdown)
% go version
go version devel +4fcceca Fri Apr 28 05:28:27 2017 +0000 darwin/amd64
```

### PR DESCRIPTION
**Pull request by tidwall**
This commit include the following updates:

  - Fixes an issue with Let's Encrypt where a publically facing website does not receive a callback from the Let's Encrypt server due to non-443 port. Now simple-httpd requires port 443 when the -l flag is specified.
  - HTTP requests will now automatcailly redirect to HTTPS when TLS is enabled. fixes #14
  - Adds support for Go 1.9 - fixes #15
  - Adds support for custom SSL certificates.
  - Updated help menu with usage and examples.
  - The -g flag now uses port 4433, otherwise all TLS use 443.
  - Added -t flag to specify a custom TLS port.
  - The -v flag displays the version information.

### CODE REVIEW

**Comment by tidwall** [comment]
FYI, I tested this on Digital Ocean at https://roam.sh using the command: 
```
nohup simple-httpd -p 80 -l roam.sh &> /tmp/nohup.out&`
```

File: main.go [hunk 1]
```diff
@@ -157,7 +170,7 @@ func (h *httpServer) ServeHTTP(w http.ResponseWriter, req *http.Request) {
 				w.Header().Set("Content-type", "text/html; charset=UTF-8")
 				w.Header().Set("Content-Length", fmt.Sprintf("%v", entry.Size()))
 
-				hf, err := os.Open(fullpath + pathSeperator + entry.Name())
+				hf, err := os.Open(filepath.Join(fullpath, entry.Name()))
```
Comment (briandowns) [inline main.go]: This makes more sense.

File: main.go [hunk 2]
```diff
@@ -290,49 +264,122 @@ func main() {
...
-		http2.ConfigureServer(&srv, new(http2.Server))
+	flag.Usage = func() {
+		w := os.Stderr
+		for _, arg := range os.Args {
+			if arg == "-?" || arg == "-h" {
+				w = os.Stdout
+				break
+			}
+		}
+		fmt.Fprintf(w, "simple-httpd version: %s\n", name+pathSeperator+version)
```
Comment (briandowns) [inline main.go]: Would there be any benefit of putting this formatted block of code in a `const` and avoid all of the writes?

File: main.go [hunk 3]
```diff
@@ -290,49 +264,122 @@ func main() {
...
+			if tlsServer == nil {
+				err = http.ListenAndServeTLS(fmt.Sprintf("0.0.0.0:%d", tlsPort), certPath, keyPath, h)
+			} else {
+				err = tlsServer.ListenAndServeTLS("", "")
+			}
+			if err != nil {
+				log.Fatal(err)
+			}
+		}()
+		time.Sleep(time.Millisecond * 10) // give a little warmup time to the TLS
```
Comment (briandowns) [inline main.go]: I"m unfamiliar with the benefit of this.

**Comment by briandowns** [comment]
What specifically did you have to do for the 1.9 compatibility?  I compiled and ran with `go1.9beta1` and everything seemed fine. I'm curious if there's a bug somewhere I'm not seeing to cause that.

File: main.go (hunk 2 above)
Comment (tidwall) [inline main.go]: One block would be cleaner for sure

File: main.go (hunk 3 above)
Comment (tidwall) [inline main.go]: I thought it might be good to give the tls server time to spins up or fail prior to logging a success message. And before opening the http server. Just a pattern that I've used in the past.

Comment (briandowns) [inline main.go]: Sounds good to me. :)

**Comment by tidwall** [comment]
I just ripped out the golang.org/x/net/http2 package. #15 mentions it doesn't work with with 1.9. The stdlib has all the http2 goodies built in.

**Comment by briandowns** [comment]
Awesome and confusing. I'll have to dig deeper and figure out why that beta binary worked. Thanks for the info.

**Comment by briandowns** [comment]
Thanks for this!

**Comment by tidwall** [comment]
You're welcome 👍
